#!/usr/bin/env python3
"""Generate Traefik HTTP routers that skip redirect-to-https for platform FQDNs.

Cloudflare Flexible SSL terminates TLS at Cloudflare and speaks HTTP to origin :80.
Coolify one-click services still attach Traefik `redirect-to-https` on the HTTP
entrypoint, which creates an infinite 302 loop for customers.

This script scans Docker labels for HTTPS routers on `*.weblines.ir` and writes
high-priority HTTP routers that point at the same Docker services — without the
redirect middleware. Safe for existing containers (no recreate required) and for
new deploys (cron keeps the file in sync within ~1 minute).

Deploy on Coolify VM:
  cp scripts/sync-weblines-http-bypass.py /home/coolify/
  chmod +x /home/coolify/sync-weblines-http-bypass.py
  python3 /home/coolify/sync-weblines-http-bypass.py
  crontab: * * * * * /usr/bin/python3 /home/coolify/sync-weblines-http-bypass.py >> /home/coolify/weblines-http-bypass.log 2>&1

Publishes via `docker cp` into coolify-proxy:/traefik/dynamic/ (coolify user cannot
write /data/coolify directly without sudo).
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

OUT = Path(os.environ.get("WEBLINES_BYPASS_OUT", "/home/coolify/zz-weblines-http-bypass.yaml"))
PROXY_DEST = os.environ.get(
    "WEBLINES_BYPASS_PROXY_DEST",
    "coolify-proxy:/traefik/dynamic/zz-weblines-http-bypass.yaml",
)
SUFFIX = os.environ.get("WEBLINES_PLATFORM_SUFFIX", ".weblines.ir")
EXCLUDE_HOSTS = {
    h.strip().lower()
    for h in os.environ.get(
        "WEBLINES_BYPASS_EXCLUDE",
        "weblines.ir,www.weblines.ir,console.weblines.ir,docs.weblines.ir",
    ).split(",")
    if h.strip()
}

HOST_RE = re.compile(r"Host\(`([^`]+)`\)")
ROUTER_RE = re.compile(r"^traefik\.http\.routers\.(https-\d+-.+)\.rule$")


def docker_names() -> list[str]:
    out = subprocess.check_output(
        ["docker", "ps", "--format", "{{.Names}}"],
        text=True,
    )
    return [n.strip() for n in out.splitlines() if n.strip()]


def labels_for(name: str) -> dict[str, str]:
    raw = subprocess.check_output(
        ["docker", "inspect", name, "--format", "{{json .Config.Labels}}"],
        text=True,
    )
    data = json.loads(raw or "{}")
    return data if isinstance(data, dict) else {}


def collect_routes() -> dict[str, str]:
    """host -> docker service name (without @docker)."""
    routes: dict[str, str] = {}
    for name in docker_names():
        try:
            labels = labels_for(name)
        except subprocess.CalledProcessError:
            continue
        for key, value in labels.items():
            m = ROUTER_RE.match(key)
            if not m or not isinstance(value, str):
                continue
            router = m.group(1)
            hm = HOST_RE.search(value)
            if not hm:
                continue
            host = hm.group(1).strip().lower()
            if not host.endswith(SUFFIX):
                continue
            if host in EXCLUDE_HOSTS:
                continue
            svc_key = f"traefik.http.routers.{router}.service"
            service = labels.get(svc_key) or router
            routes[host] = service
    return dict(sorted(routes.items()))


def render(routes: dict[str, str]) -> str:
    lines = [
        "# AUTO-GENERATED by sync-weblines-http-bypass.py — do not edit.",
        "# Cloudflare Flexible: serve platform FQDNs on HTTP without HTTPS redirect.",
        "http:",
        "  routers:",
    ]
    if not routes:
        lines.append("    # (no platform HTTPS routers found)")
        return "\n".join(lines) + "\n"

    for i, (host, service) in enumerate(routes.items()):
        safe = re.sub(r"[^a-zA-Z0-9]+", "-", host).strip("-")[:80]
        name = f"weblines-http-{i}-{safe}"
        lines.append(f"    {name}:")
        lines.append(f'      rule: "Host(`{host}`)"')
        lines.append("      entryPoints:")
        lines.append("        - http")
        lines.append("      priority: 1000")
        lines.append(f"      service: {service}@docker")
    return "\n".join(lines) + "\n"


def atomic_write(path: Path, content: str) -> bool:
    path.parent.mkdir(parents=True, exist_ok=True)
    prev = path.read_text() if path.exists() else None
    if prev == content:
        return False
    with tempfile.NamedTemporaryFile("w", dir=str(path.parent), delete=False) as tmp:
        tmp.write(content)
        tmp.flush()
        os.fsync(tmp.fileno())
        tmp_name = tmp.name
    os.replace(tmp_name, path)
    return True


def publish_to_proxy(path: Path) -> None:
    subprocess.check_call(["docker", "cp", str(path), PROXY_DEST])
    # Remove obsolete one-off single-host bypass if present
    subprocess.call(
        [
            "docker",
            "exec",
            "coolify-proxy",
            "rm",
            "-f",
            "/traefik/dynamic/zz-weblines-no-https-redirect-routers.yaml",
        ]
    )


def main() -> int:
    routes = collect_routes()
    content = render(routes)
    changed = atomic_write(OUT, content)
    publish_to_proxy(OUT)
    print(f"hosts={len(routes)} changed={changed} published=ok")
    return 0


if __name__ == "__main__":
    sys.exit(main())
